name: Publish Preview
on:
  push:
    branches:
    - 'preview/**'
    paths:
    - '!test/**'
    - '**.js'
    - '**.coffee'
    - '**.json'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: change scope in package.json
        run: |
          mv package.json package.original.json
          jq --arg scope ${{github.actor}} \
            '.name|= sub("^";"@"+$scope+"/")|.repository.url|=sub("fedwiki";$scope)' \
            package.original.json \
            > package.json
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@${{github.actor}}"
      - name: publish package
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
        run: |
          npm ci
          PRERELEASE=$(
            git branch --show-current \
            | perl -pe 's/_/-/g;s/[^0-9A-Za-z-]//g' )
          npm version prepatch \
            --preid=$PRERELEASE-$(git rev-parse --short HEAD)-${{github.run_number}} \
            --no-git-tag-version \
            --force
          npm run build
          npm publish
